<?xml version="1.0"?>
<package format="3">
  <name>sc_relocalization</name>
  <version>0.0.1</version>
  <description>Standalone ScanContext Relocalization Node</description>
  <maintainer email="user@example.com">User</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>livox_ros_driver2</depend>
  <depend>pcl_conversions</depend>
  <depend>PCL</depend>
  <depend>Eigen3</depend>
  <depend>yaml-cpp</depend>
  <depend>small_gicp</depend>
  <depend>qtbase5-dev</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
