<?xml version="1.0"?>
<package format="3">
  <name>connector_action_manager</name>
  <version>0.1.0</version>
  <description>Connector action manager for topology-aware semantic navigation.</description>
  <maintainer email="todo@example.com">origin_nav</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>geometry_msgs</depend>
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>topology_global_planner</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
